name: .NET Core

on:
  push:
    branches: [ master, pixenary, balderdash ]
  pull_request:
    branches: [ master, pixenary, balderdash ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Deploy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }} 
      run : |
            docker build -t release -f src/Dockerfile .
            curl https://cli-assets.heroku.com/install.sh | sh
            docker login --username=_ --password $HEROKU_API_KEY registry.heroku.com
            docker tag release registry.heroku.com/games-by-joshua/web
            docker push registry.heroku.com/games-by-joshua/web
            heroku container:release web --app games-by-joshua


