name: .NET Core

on:
  push:
    branches: [ master, pixenary ]
  pull_request:
    branches: [ master, pixenary ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: build image
      run: |
        docker info
        docker build -t release -f src/Dockerfile .
    - name: deploy
      run: |
        docker login --username=joshuaquarryhouse@gmail.com --password=402b1ef9-d3ba-4acd-ac79-f032566d87ba registry.heroku.com
        docker tag release registry.heroku.com/games-by-joshua/web
        docker push registry.heroku.com/games-by-joshua/web
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:release web -a games-by-joshua
